apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: httpd:2.4.54-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: "/usr/local/apache2/htdocs/"
          name: httpd-storage
      volumes:
        - name: httpd-storage
          persistentVolumeClaim:
            claimName: backend-claim

---
apiVersion: v1
kind: Service
metadata:
  name: website-service-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: website
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80



#kubectl cp ./website/ website-deployment-5b67589755-jzt7m:/usr/local/apache2/htdocs/